"""initial

Revision ID: 1c3c2c7bc925
Revises: 
Create Date: 2026-05-20 18:44:11.672187+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3c2c7bc925'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('athlete', 'coach', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('athlete_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('gender', sa.Enum('m', 'f', name='gender_enum'), nullable=False),
    sa.Column('qualification', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('training_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('target_event', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DATE(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['training_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'athlete_id')
    )
    op.create_table('physiological_markers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('date_recorded', sa.DATE(), nullable=False),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('threshold_hr', sa.Integer(), nullable=True),
    sa.Column('hrv_baseline', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('measured', 'formula', name='marker_source'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('target_intensity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['training_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjective_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('date_recorded', sa.DATE(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('fatigue_level', sa.Integer(), nullable=True),
    sa.Column('hrv_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'date_recorded')
    )
    op.create_table('training_load_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('daily_tss', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('atl_7d', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ctl_42d', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('tsb', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'date')
    )
    op.create_table('individual_workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('marker_id_used', sa.UUID(), nullable=True),
    sa.Column('planned_date', sa.DATE(), nullable=False),
    sa.Column('planned_duration_min', sa.Integer(), nullable=True),
    sa.Column('planned_tss', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('k_qual', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('k_form', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('target_zone', sa.String(length=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'completed', name='workout_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['marker_id_used'], ['physiological_markers.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['plan_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actual_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('imported', 'manual', name='telemetry_source'), nullable=False),
    sa.Column('actual_duration_min', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('actual_tss', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hr_zone1_min', sa.Integer(), nullable=True),
    sa.Column('hr_zone2_min', sa.Integer(), nullable=True),
    sa.Column('hr_zone3_min', sa.Integer(), nullable=True),
    sa.Column('hr_zone4_min', sa.Integer(), nullable=True),
    sa.Column('hr_zone5_min', sa.Integer(), nullable=True),
    sa.Column('raw_file_path', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['individual_workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id')
    )
    op.create_table('diagnostic_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_workout_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by_subjective_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity'), nullable=False),
    sa.Column('rule_code', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_subjective_id'], ['subjective_metrics.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_workout_id'], ['individual_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnostic_alerts')
    op.drop_table('actual_telemetry')
    op.drop_table('individual_workouts')
    op.drop_table('training_load_history')
    op.drop_table('subjective_metrics')
    op.drop_table('plan_templates')
    op.drop_table('physiological_markers')
    op.drop_table('group_memberships')
    op.drop_table('training_groups')
    op.drop_table('athlete_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
